version: '3'
services:
  ks-dms-dev:
    image: docker-registry.imcloudep.com/imcloud_dms:v1
    restart: always
    environment:
      - EUREKA_SERVER_ADDRESS=core-eureka
    volumes:
      - /mnt/cnc_server2/logs:/opt/cnc_server2/logs

  # mongodb:
  #     image: mongo
  #     ports:
  #       - "27017:27017"
  #     volumes:
  #       - /data/db:/data/db
  #       - /data/configdb:/data/configdb
networks:
  default:
    external:
      name: imcloudep-overlay
